import * as iter from "./iter"

test("backwards-rune", () => {
	expect(iter.rtl.rune("")).toBe("")
	expect(iter.rtl.rune("\n")).toBe("\n")
	expect(iter.rtl.rune("\n\n")).toBe("\n")
	expect(iter.rtl.rune("Hello")).toBe("o")
	expect(iter.rtl.rune("Hello,")).toBe(",")
	expect(iter.rtl.rune("Hello, ")).toBe(" ")
	expect(iter.rtl.rune("Hello, world")).toBe("d")
	expect(iter.rtl.rune("Hello, world!")).toBe("!")
	expect(iter.rtl.rune("Hello, world! ")).toBe(" ")
	expect(iter.rtl.rune("Hello, world! 😀")).toBe("😀")
	expect(iter.rtl.rune("Hello, world! 😀\n")).toBe("\n")
	expect(iter.rtl.rune("Hello, world! 😀\n\n")).toBe("\n")
})

test("backwards-word", () => {
	expect(iter.rtl.word("")).toBe("")
	expect(iter.rtl.word("\n")).toBe("\n")
	expect(iter.rtl.word("\n\n")).toBe("\n")
	expect(iter.rtl.word("Hello")).toBe("Hello")
	expect(iter.rtl.word("Hello,")).toBe(",")
	expect(iter.rtl.word("Hello, ")).toBe(", ")
	expect(iter.rtl.word("Hello, world")).toBe("world")
	expect(iter.rtl.word("Hello, world!")).toBe("!")
	expect(iter.rtl.word("Hello, world! ")).toBe("! ")
	expect(iter.rtl.word("Hello, world! 😀")).toBe("😀")
	expect(iter.rtl.word("Hello, world! 😀\n")).toBe("\n")
	expect(iter.rtl.word("Hello, world! 😀\n\n")).toBe("\n")
})

test("backwards-line", () => {
	expect(iter.rtl.line("")).toBe("")
	expect(iter.rtl.line("\n")).toBe("\n")
	expect(iter.rtl.line("\n\n")).toBe("\n")
	expect(iter.rtl.line("Hello")).toBe("Hello")
	expect(iter.rtl.line("Hello,")).toBe("Hello,")
	expect(iter.rtl.line("Hello, ")).toBe("Hello, ")
	expect(iter.rtl.line("Hello, world")).toBe("Hello, world")
	expect(iter.rtl.line("Hello, world!")).toBe("Hello, world!")
	expect(iter.rtl.line("Hello, world! ")).toBe("Hello, world! ")
	expect(iter.rtl.line("Hello, world! 😀")).toBe("Hello, world! 😀")
	expect(iter.rtl.line("Hello, world! 😀\n")).toBe("\n")
	expect(iter.rtl.line("Hello, world! 😀\n\n")).toBe("\n")
})

test("forwards-rune", () => {
	expect(iter.ltr.rune("\n\n😀 !dlrow ,olleH")).toBe("\n")
	expect(iter.ltr.rune("\n😀 !dlrow ,olleH")).toBe("\n")
	expect(iter.ltr.rune("😀 !dlrow ,olleH")).toBe("😀")
	expect(iter.ltr.rune(" !dlrow ,olleH")).toBe(" ")
	expect(iter.ltr.rune("!dlrow ,olleH")).toBe("!")
	expect(iter.ltr.rune("dlrow ,olleH")).toBe("d")
	expect(iter.ltr.rune(" ,olleH")).toBe(" ")
	expect(iter.ltr.rune(",olleH")).toBe(",")
	expect(iter.ltr.rune("olleH")).toBe("o")
	expect(iter.ltr.rune("\n\n")).toBe("\n")
	expect(iter.ltr.rune("\n")).toBe("\n")
	expect(iter.ltr.rune("")).toBe("")
})

test("forwards-word", () => {
	expect(iter.ltr.word("\n\n😀 !dlrow ,olleH")).toBe("\n")
	expect(iter.ltr.word("\n😀 !dlrow ,olleH")).toBe("\n")
	expect(iter.ltr.word("😀 !dlrow ,olleH")).toBe("😀")
	expect(iter.ltr.word(" !dlrow ,olleH")).toBe(" !")
	expect(iter.ltr.word("!dlrow ,olleH")).toBe("!")
	expect(iter.ltr.word("dlrow ,olleH")).toBe("dlrow")
	expect(iter.ltr.word(" ,olleH")).toBe(" ,")
	expect(iter.ltr.word(",olleH")).toBe(",")
	expect(iter.ltr.word("olleH")).toBe("olleH")
	expect(iter.ltr.word("\n\n")).toBe("\n")
	expect(iter.ltr.word("\n")).toBe("\n")
	expect(iter.ltr.word("")).toBe("")
})
