import * as ltr from "./ltr"

test("ltr.rune(...)", () => {
	expect(ltr.rune("\n\n😀 !dlrow ,olleH\n\n")).toBe("\n")
	expect(ltr.rune("\n😀 !dlrow ,olleH\n\n")).toBe("\n")
	expect(ltr.rune("😀 !dlrow ,olleH\n\n")).toBe("😀")
	expect(ltr.rune(" !dlrow ,olleH\n\n")).toBe(" ")
	expect(ltr.rune("!dlrow ,olleH\n\n")).toBe("!")
	expect(ltr.rune("dlrow ,olleH\n\n")).toBe("d")
	expect(ltr.rune(" ,olleH\n\n")).toBe(" ")
	expect(ltr.rune(",olleH\n\n")).toBe(",")
	expect(ltr.rune("olleH\n\n")).toBe("o")
	expect(ltr.rune("\n\n")).toBe("\n")
	expect(ltr.rune("\n")).toBe("\n")
	expect(ltr.rune("")).toBe("")
})

test("ltr.word(...)", () => {
	expect(ltr.word("\n\n😀 !dlrow ,olleH\n\n")).toBe("\n")
	expect(ltr.word("\n😀 !dlrow ,olleH\n\n")).toBe("\n")
	expect(ltr.word("😀 !dlrow ,olleH\n\n")).toBe("😀")
	expect(ltr.word(" !dlrow ,olleH\n\n")).toBe(" !")
	expect(ltr.word("!dlrow ,olleH\n\n")).toBe("!")
	expect(ltr.word("dlrow ,olleH\n\n")).toBe("dlrow")
	expect(ltr.word(" ,olleH\n\n")).toBe(" ,")
	expect(ltr.word(",olleH\n\n")).toBe(",")
	expect(ltr.word("olleH\n\n")).toBe("olleH")
	expect(ltr.word("\n\n")).toBe("\n")
	expect(ltr.word("\n")).toBe("\n")
	expect(ltr.word("")).toBe("")
})
