import iota from "./index"

test("iota()", () => {
	const i = iota()
	expect(i()).toBe(0)
	expect(i()).toBe(1)
	expect(i()).toBe(2)
	expect(i()).toBe(3)
	expect(i()).toBe(4)
	expect(i()).toBe(5)
	expect(i()).toBe(6)
	expect(i()).toBe(7)
	expect(i()).toBe(8)
	expect(i()).toBe(9)
})

test("iota(-1)", () => {
	const i = iota(-1)
	expect(i()).toBe(-1)
	expect(i()).toBe(0)
	expect(i()).toBe(1)
	expect(i()).toBe(2)
	expect(i()).toBe(3)
	expect(i()).toBe(4)
	expect(i()).toBe(5)
	expect(i()).toBe(6)
	expect(i()).toBe(7)
	expect(i()).toBe(8)
	expect(i()).toBe(9)
})
