import * as Iterators from "./index"

test("rtl-rune", () => {
	expect(Iterators.RTL.rune("")).toBe("")
	expect(Iterators.RTL.rune("\n")).toBe("\n")
	expect(Iterators.RTL.rune("\n\n")).toBe("\n")
	expect(Iterators.RTL.rune("\n\nHello")).toBe("o")
	expect(Iterators.RTL.rune("\n\nHello,")).toBe(",")
	expect(Iterators.RTL.rune("\n\nHello, ")).toBe(" ")
	expect(Iterators.RTL.rune("\n\nHello, world")).toBe("d")
	expect(Iterators.RTL.rune("\n\nHello, world!")).toBe("!")
	expect(Iterators.RTL.rune("\n\nHello, world! ")).toBe(" ")
	expect(Iterators.RTL.rune("\n\nHello, world! 😀")).toBe("😀")
	expect(Iterators.RTL.rune("\n\nHello, world! 😀\n")).toBe("\n")
	expect(Iterators.RTL.rune("\n\nHello, world! 😀\n\n")).toBe("\n")
})

test("rtl-word", () => {
	expect(Iterators.RTL.word("")).toBe("")
	expect(Iterators.RTL.word("\n")).toBe("\n")
	expect(Iterators.RTL.word("\n\n")).toBe("\n")
	expect(Iterators.RTL.word("\n\nHello")).toBe("Hello")
	expect(Iterators.RTL.word("\n\nHello,")).toBe(",")
	expect(Iterators.RTL.word("\n\nHello, ")).toBe(", ")
	expect(Iterators.RTL.word("\n\nHello, world")).toBe("world")
	expect(Iterators.RTL.word("\n\nHello, world!")).toBe("!")
	expect(Iterators.RTL.word("\n\nHello, world! ")).toBe("! ")
	expect(Iterators.RTL.word("\n\nHello, world! 😀")).toBe("😀")
	expect(Iterators.RTL.word("\n\nHello, world! 😀\n")).toBe("\n")
	expect(Iterators.RTL.word("\n\nHello, world! 😀\n\n")).toBe("\n")
})

test("rtl-line", () => {
	expect(Iterators.RTL.line("")).toBe("")
	expect(Iterators.RTL.line("\n")).toBe("\n")
	expect(Iterators.RTL.line("\n\n")).toBe("\n")
	expect(Iterators.RTL.line("\n\nHello")).toBe("Hello")
	expect(Iterators.RTL.line("\n\nHello,")).toBe("Hello,")
	expect(Iterators.RTL.line("\n\nHello, ")).toBe("Hello, ")
	expect(Iterators.RTL.line("\n\nHello, world")).toBe("Hello, world")
	expect(Iterators.RTL.line("\n\nHello, world!")).toBe("Hello, world!")
	expect(Iterators.RTL.line("\n\nHello, world! ")).toBe("Hello, world! ")
	expect(Iterators.RTL.line("\n\nHello, world! 😀")).toBe("Hello, world! 😀")
	expect(Iterators.RTL.line("\n\nHello, world! 😀\n")).toBe("\n")
	expect(Iterators.RTL.line("\n\nHello, world! 😀\n\n")).toBe("\n")
})

test("ltr-rune", () => {
	expect(Iterators.LTR.rune("\n\n😀 !dlrow ,olleH\n\n")).toBe("\n")
	expect(Iterators.LTR.rune("\n😀 !dlrow ,olleH\n\n")).toBe("\n")
	expect(Iterators.LTR.rune("😀 !dlrow ,olleH\n\n")).toBe("😀")
	expect(Iterators.LTR.rune(" !dlrow ,olleH\n\n")).toBe(" ")
	expect(Iterators.LTR.rune("!dlrow ,olleH\n\n")).toBe("!")
	expect(Iterators.LTR.rune("dlrow ,olleH\n\n")).toBe("d")
	expect(Iterators.LTR.rune(" ,olleH\n\n")).toBe(" ")
	expect(Iterators.LTR.rune(",olleH\n\n")).toBe(",")
	expect(Iterators.LTR.rune("olleH\n\n")).toBe("o")
	expect(Iterators.LTR.rune("\n\n")).toBe("\n")
	expect(Iterators.LTR.rune("\n")).toBe("\n")
	expect(Iterators.LTR.rune("")).toBe("")
})

test("ltr-word", () => {
	expect(Iterators.LTR.word("\n\n😀 !dlrow ,olleH\n\n")).toBe("\n")
	expect(Iterators.LTR.word("\n😀 !dlrow ,olleH\n\n")).toBe("\n")
	expect(Iterators.LTR.word("😀 !dlrow ,olleH\n\n")).toBe("😀")
	expect(Iterators.LTR.word(" !dlrow ,olleH\n\n")).toBe(" !")
	expect(Iterators.LTR.word("!dlrow ,olleH\n\n")).toBe("!")
	expect(Iterators.LTR.word("dlrow ,olleH\n\n")).toBe("dlrow")
	expect(Iterators.LTR.word(" ,olleH\n\n")).toBe(" ,")
	expect(Iterators.LTR.word(",olleH\n\n")).toBe(",")
	expect(Iterators.LTR.word("olleH\n\n")).toBe("olleH")
	expect(Iterators.LTR.word("\n\n")).toBe("\n")
	expect(Iterators.LTR.word("\n")).toBe("\n")
	expect(Iterators.LTR.word("")).toBe("")
})
