import getKeyCode from "./index"

test("", () => {
	expect(getKeyCode("Escape")).toBe(27)

	expect(getKeyCode("`")).toBe(192)
	expect(getKeyCode("1")).toBe(49)
	expect(getKeyCode("2")).toBe(50)
	expect(getKeyCode("3")).toBe(51)
	expect(getKeyCode("4")).toBe(52)
	expect(getKeyCode("5")).toBe(53)
	expect(getKeyCode("6")).toBe(54)
	expect(getKeyCode("7")).toBe(55)
	expect(getKeyCode("8")).toBe(56)
	expect(getKeyCode("9")).toBe(57)
	expect(getKeyCode("0")).toBe(48)
	expect(getKeyCode("-")).toBe(189)
	expect(getKeyCode("=")).toBe(187)
	expect(getKeyCode("Backspace")).toBe(8)
	expect(getKeyCode("Delete")).toBe(46)

	expect(getKeyCode("Tab")).toBe(9)
	expect(getKeyCode("Q")).toBe(81)
	expect(getKeyCode("W")).toBe(87)
	expect(getKeyCode("E")).toBe(69)
	expect(getKeyCode("R")).toBe(82)
	expect(getKeyCode("T")).toBe(84)
	expect(getKeyCode("Y")).toBe(89)
	expect(getKeyCode("U")).toBe(85)
	expect(getKeyCode("I")).toBe(73)
	expect(getKeyCode("O")).toBe(79)
	expect(getKeyCode("P")).toBe(80)
	expect(getKeyCode("[")).toBe(219)
	expect(getKeyCode("]")).toBe(221)
	expect(getKeyCode("\\")).toBe(220)

	expect(getKeyCode("CapsLock")).toBe(20)
	expect(getKeyCode("A")).toBe(65)
	expect(getKeyCode("S")).toBe(83)
	expect(getKeyCode("D")).toBe(68)
	expect(getKeyCode("F")).toBe(70)
	expect(getKeyCode("G")).toBe(71)
	expect(getKeyCode("H")).toBe(72)
	expect(getKeyCode("J")).toBe(74)
	expect(getKeyCode("K")).toBe(75)
	expect(getKeyCode("L")).toBe(76)
	expect(getKeyCode(";")).toBe(186)
	expect(getKeyCode("'")).toBe(222)
	expect(getKeyCode("Enter")).toBe(13)

	expect(getKeyCode("Shift")).toBe(16)
	expect(getKeyCode("Z")).toBe(90)
	expect(getKeyCode("X")).toBe(88)
	expect(getKeyCode("C")).toBe(67)
	expect(getKeyCode("V")).toBe(86)
	expect(getKeyCode("B")).toBe(66)
	expect(getKeyCode("N")).toBe(78)
	expect(getKeyCode("M")).toBe(77)
	expect(getKeyCode(",")).toBe(188)
	expect(getKeyCode(".")).toBe(190)
	expect(getKeyCode("/")).toBe(191)

	expect(getKeyCode("Control")).toBe(17)
	expect(getKeyCode("Alt")).toBe(18)
	expect(getKeyCode("Meta")).toBe(91)
	expect(getKeyCode("Space")).toBe(32)
	expect(getKeyCode("ArrowLeft")).toBe(37)
	expect(getKeyCode("ArrowUp")).toBe(38)
	expect(getKeyCode("ArrowDown")).toBe(40)
	expect(getKeyCode("ArrowRight")).toBe(39)
})
